name: n8n_client
description: A Dart client for interacting with the n8n Public API, built by Spinex IO.
version: 0.1.0
homepage: https://spinex.io
repository: https://github.com/mskayali/n8n_client
issue_tracker: https://github.com/spinex-io/n8n_client/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0

publish_to: 'none' # Remove this line if you want to publish to pub.dev later
